# Generated by Django 6.0.5 on 2026-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/'),
        ),
    ]
