# Generated by Django 6.0.5 on 2026-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_landuseplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseplan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landuseplan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
