# Generated by Django 6.0.5 on 2026-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_landuseplan_latitude_landuseplan_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseplan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=10),
        ),
    ]
